### ISSUE TITLE
Cannot apply only some of the `keyManagement.awsKms` values

### ISSUE THREAD

**Issue by ssedrick** [Soluto/helm-charts#45]
I am attempting to deploy the helm chart with the following values:

```yaml
keyManagement:
    provider: AwsKms
    awsKms:
        region: us-east-1
        cmkPrefix: some-prefix
```

This fails due to the following error:

> unable to build kubernetes objects from release manifest: error validating "": error validating data: [unknown object type "nil" in ConfigMap.data.KeyManagement__AwsKms__Key, unknown object type "nil" in ConfigMap.data.KeyManagement__AwsKms__Secret]

I don't want to provide the credentials in this manner. It would be nice if I could provide only some of the values and not `key` and `secret`.
